PROGRAM = opencode-system-roots-smoke
GO_PACKAGE = main
ROOT = ../../../..
PACKAGE_DIRS = kos os crypto/x509 net/http io fmt errors time
BUILD_CACHE_NAMESPACE = opencode-stdlib
include $(ROOT)/tooling/kolibri-app.mk
