PROGRAM = vncsrv
PACKAGE_DIRS = kos errors io bytes syscall time os fmt strings net bufio image runtime log encoding/binary sync strconv github.com/bradfitz/rfbgo/rfb
ROOT = ../..

include $(ROOT)/tooling/kolibri-app.mk
