PROGRAM = duitxdemo
PACKAGE_DIRS = kos github.com/mjl-/duit 9fans.net/go/draw github.com/psilva261/mycel/browser/duitx github.com/psilva261/mycel/logger
ROOT = ../../..

include $(ROOT)/tooling/kolibri-app.mk
