PROGRAM = opencode-secure-random-smoke
GO_PACKAGE = main
ROOT = ../../../..
PACKAGE_DIRS = kos os crypto/rand crypto/ed25519 bytes
BUILD_CACHE_NAMESPACE = opencode-stdlib
include $(ROOT)/tooling/kolibri-app.mk
