PROGRAM = tagix_browser
PACKAGE_DIRS = kos ui io strings net/url net/html net/http net/http/cookiejar os fmt bytes image image/gif image/jpeg image/png encoding/base64 crypto/sha1 golang.org/x/image/webp golang.org/x/net/publicsuffix
ROOT = ../..

include $(ROOT)/tooling/kolibri-app.mk
