#define SQLITE_OS_OTHER 1
#define SQLITE_THREADSAFE 0
#define SQLITE_OMIT_WAL 1
#define SQLITE_DEFAULT_MEMSTATUS 0
#define SQLITE_OMIT_LOAD_EXTENSION 1
#define SQLITE_OMIT_SHARED_CACHE 1
#define SQLITE_TEMP_STORE 3
#define HAVE_LOCALTIME_R 1
#define HAVE_GMTIME_R 1

#include "upstream/sqlite3.c"
