PROGRAM = opencode-local-types-smoke
GO_PACKAGE = main
ROOT = ../../../..
PACKAGE_DIRS = kos
BUILD_CACHE_NAMESPACE = opencode-smoke
THIRD_PARTY_DIRS = $(ROOT_ABS)/tooling/gccgo/tests/local-types

include $(ROOT)/tooling/kolibri-app.mk
