PROGRAM = mycel
PACKAGE_DIRS = kos github.com/mjl-/duit 9fans.net/go/draw github.com/psilva261/mycel/browser github.com/psilva261/mycel/js github.com/psilva261/mycel/img
ROOT = ../..

include $(ROOT)/tooling/kolibri-app.mk
