; goro loads this file from the same directory as goro.kex.
[PHP]
default_charset = "UTF-8"
display_errors = On
file_uploads = Off
html_errors = Off
include_path = "."
max_execution_time = 30
memory_limit = 32M
output_buffering = Off
register_argc_argv = On
variables_order = "EGPCS"
