PROGRAM = go9pdemo
PACKAGE_DIRS = kos ui ui/elements 9fans.net/go/plan9 9fans.net/go/plan9/client github.com/knusbaum/go9p github.com/knusbaum/go9p/fs
ROOT = ../../..

include $(ROOT)/tooling/kolibri-app.mk
