#!/usr/bin/env python3

import argparse
import sys


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate KolibriOS EXPORTS table assembly.")
    parser.add_argument("--package", required=True, help="Go package name for symbol prefixing.")
    parser.add_argument("--input", required=True, help="Path to exports definition file.")
    parser.add_argument("--output", required=True, help="Path to write generated assembly.")
    parser.add_argument("--c-output", help="Optional path to write generated C stubs.")
    parser.add_argument(
        "--stub-mode",
        choices=("direct", "bootstrap"),
        default="direct",
        help="Stub mode when generating C output.",
    )
    parser.add_argument(
        "--stub-strict",
        type=int,
        default=1,
        help="Require explicit arg counts for stubs (1/0).",
    )
    return parser.parse_args()


def clean_line(line: str) -> str:
    if "#" in line:
        line = line.split("#", 1)[0]
    return line.strip()


def escape_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace("\"", "\\\"")


def parse_name_and_args(value: str):
    text = value.strip()
    if text.endswith(")") and "(" in text:
        idx = text.rfind("(")
        maybe = text[idx + 1 : -1].strip()
        if maybe.isdigit():
            name = text[:idx].strip()
            return name, int(maybe)
    return text, None


def parse_exports(path: str, package: str):
    exports = []
    with open(path, "r", encoding="utf-8") as handle:
        for index, raw in enumerate(handle, start=1):
            line = clean_line(raw)
            if not line:
                continue
            name = ""
            symbol = ""
            if "->" in line:
                name, symbol = line.split("->", 1)
            elif "=" in line:
                name, symbol = line.split("=", 1)
            else:
                parts = line.split()
                if len(parts) == 1:
                    name = parts[0]
                elif len(parts) == 2:
                    name, symbol = parts
                else:
                    raise ValueError(f"invalid exports line {index}: {raw.strip()}")
            name = name.strip()
            symbol = symbol.strip()
            name, argc = parse_name_and_args(name)
            if not name:
                raise ValueError(f"invalid exports line {index}: empty export name")
            raw_symbol = False
            if symbol:
                if symbol.startswith("@"):
                    raw_symbol = True
                    resolved = symbol[1:]
                else:
                    resolved = f"go_0{package}.{symbol}"
            else:
                resolved = f"go_0{package}.{name}"
            if not resolved:
                raise ValueError(f"invalid exports line {index}: empty symbol")
            exports.append(
                {
                    "name": name,
                    "resolved": resolved,
                    "raw": raw_symbol,
                    "argc": argc,
                    "line": index,
                    "text": raw.strip(),
                }
            )
    if not exports:
        raise ValueError("exports file contains no entries")
    return exports


def short_export_label(index: int) -> str:
    if index >= 10000:
        raise ValueError(f"export index {index} exceeds 9999 (short label limit)")
    return f"exn{index:04d}"


def stub_symbol(index: int) -> str:
    if index >= 10000:
        raise ValueError(f"export index {index} exceeds 9999 (stub name limit)")
    return f"kexp{index:04d}"


def write_output(path: str, exports, use_stubs: bool):
    symbols = []
    for index, entry in enumerate(exports):
        if use_stubs and not entry["raw"]:
            symbol = stub_symbol(index)
        else:
            symbol = entry["resolved"]
        if symbol not in symbols:
            symbols.append(symbol)

    with open(path, "w", encoding="utf-8", newline="\n") as out:
        out.write("/* generated by gen-kolibri-exports.py */\n")
        out.write("    .section .rodata\n")
        out.write("    .align 4\n")
        for index, entry in enumerate(exports):
            label = short_export_label(index)
            out.write(f"    .globl {label}\n")
            out.write(f"{label}:\n")
            out.write(f"    .ascii \"{escape_string(entry['name'])}\\0\"\n")
        out.write("\n")
        out.write("    .section .data\n")
        out.write("    .align 16\n")
        out.write("    .globl EXPORTS\n")
        out.write("    .type EXPORTS, @object\n")
        out.write(f"    .size EXPORTS, {len(exports) * 8 + 4}\n")
        out.write("EXPORTS:\n")
        for index, entry in enumerate(exports):
            label = short_export_label(index)
            if use_stubs and not entry["raw"]:
                symbol = stub_symbol(index)
            else:
                symbol = entry["resolved"]
            out.write(f"    .long {label}\n")
            out.write(f"    .long {symbol}\n")
        out.write("    .long 0\n\n")
        for symbol in symbols:
            out.write(f"    .extern {symbol}\n")


def write_stubs_c(path: str, exports, package: str, mode: str, strict: bool):
    if mode not in ("direct", "bootstrap"):
        raise ValueError(f"unsupported stub mode: {mode}")
    go_init_symbol = f"go.{package}..import"
    with open(path, "w", encoding="utf-8", newline="\n") as out:
        out.write("/* generated by gen-kolibri-exports.py */\n")
        out.write("#include <stdint.h>\n\n")
        out.write("#define KOS_STDCALL __attribute__((stdcall))\n\n")
        if mode == "bootstrap":
            out.write("extern void runtime_gc_set_stack_top(const void* ptr);\n")
            out.write("extern void runtime_kolibri_start(void (*init)(void), void (*main)(void));\n")
            out.write(
                f"extern void go_init(void) __asm__(\"{escape_string(go_init_symbol)}\");\n\n"
            )
        else:
            out.write("extern void runtime_gc_set_stack_top(const void* ptr);\n")
            out.write(
                f"extern void go_init(void) __asm__(\"{escape_string(go_init_symbol)}\");\n"
            )
            out.write("int kexpinit = 0;\n")
            out.write("static void kolibri_exports_enter(void) {\n")
            out.write("    unsigned char stack_top_marker = 0;\n")
            out.write("    runtime_gc_set_stack_top(&stack_top_marker);\n")
            out.write("    if (!kexpinit) {\n")
            out.write("        go_init();\n")
            out.write("        kexpinit = 1;\n")
            out.write("    }\n")
            out.write("}\n\n")

        for index, entry in enumerate(exports):
            if entry["raw"]:
                continue
            argc = entry["argc"]
            if argc is None:
                if strict:
                    raise ValueError(
                        f"missing arg count for export '{entry['name']}' on line {entry['line']}"
                    )
                argc = 0
            if argc < 0:
                raise ValueError(
                    f"invalid arg count for export '{entry['name']}' on line {entry['line']}"
                )
            if mode == "bootstrap" and argc != 0:
                raise ValueError(
                    f"bootstrap stubs require 0 args for export '{entry['name']}' on line {entry['line']}"
                )

            c_sym = f"go_sym_{index}"
            if mode == "bootstrap":
                out.write(
                    f"extern void {c_sym}(void) __asm__(\"{escape_string(entry['resolved'])}\");\n"
                )
            else:
                args = ", ".join(f"uint32_t a{i}" for i in range(argc))
                proto_args = args if args else "void"
                out.write(
                    f"extern uint32_t {c_sym}({proto_args}) __asm__(\"{escape_string(entry['resolved'])}\");\n"
                )

        out.write("\n")
        for index, entry in enumerate(exports):
            if entry["raw"]:
                continue
            argc = entry["argc"]
            if argc is None:
                argc = 0
            wrapper = stub_symbol(index)
            if mode == "bootstrap":
                out.write(f"void KOS_STDCALL {wrapper}(void) {{\n")
                out.write("    unsigned char stack_top_marker = 0;\n")
                out.write("    runtime_gc_set_stack_top(&stack_top_marker);\n")
                out.write(f"    runtime_kolibri_start(go_init, go_sym_{index});\n")
                out.write("}\n\n")
            else:
                args = ", ".join(f"uint32_t a{i}" for i in range(argc))
                proto_args = args if args else "void"
                call_args = ", ".join(f"a{i}" for i in range(argc))
                out.write(f"uint32_t KOS_STDCALL {wrapper}({proto_args}) {{\n")
                out.write("    kolibri_exports_enter();\n")
                if call_args:
                    out.write(f"    return go_sym_{index}({call_args});\n")
                else:
                    out.write(f"    return go_sym_{index}();\n")
                out.write("}\n\n")


def main() -> int:
    args = parse_args()
    try:
        exports = parse_exports(args.input, args.package)
        use_stubs = args.c_output is not None
        write_output(args.output, exports, use_stubs)
        if args.c_output:
            write_stubs_c(
                args.c_output,
                exports,
                args.package,
                args.stub_mode,
                args.stub_strict != 0,
            )
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
