#!/usr/bin/env python3
"""Regenerate unchanged OpenSSL 386 CPU random routines for the native ABI."""
from pathlib import Path
import hashlib
import json
import subprocess
import tempfile

root=Path(__file__).resolve().parent.parent
upstream=root/'third_party/openssl-rand'
manifest=json.loads((upstream/'UPSTREAM.json').read_text())
for name,expected in manifest['files'].items():
    if hashlib.sha256((upstream/name).read_bytes()).hexdigest()!=expected:
        raise RuntimeError('OpenSSL upstream source changed: '+name)
with tempfile.TemporaryDirectory(prefix='kolibri-cpu-random-') as temporary:
    generated=Path(temporary)/'x86cpuid.S'
    subprocess.run(['perl',str(upstream/'crypto/x86cpuid.pl'),'elf',str(generated)],check=True)
    assembly=generated.read_text()
first=assembly.index('.globl\tOPENSSL_ia32_rdrand_bytes')
last=assembly.index('.size\tOPENSSL_ia32_rdseed_bytes')
last=assembly.index('\n',last)+1
header='''/* Copyright 2004-2020 The OpenSSL Project Authors. All Rights Reserved.
 * Apache License 2.0: third_party/openssl-rand/LICENSE.txt
 * Extracted unchanged generated byte routines from OpenSSL 3.0.15
 * crypto/x86cpuid.pl; regeneration/provenance in third_party/openssl-rand. */
.text
'''
target=root/'platform/abi/runtime_entropy_386.S'
data=header+assembly[first:last]+'\n.section .note.GNU-stack,"",@progbits\n'
if not target.exists() or target.read_text()!=data:
    target.write_text(data)
print('Verified/generated upstream CPU random byte routines:',target)
